name: Github GraphQL API Query
on:
  push:
    branches:
      - master

jobs:
  pullRequestDataFetch:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.0.0
        id: get_pull_requests_data
        with:
          query: |
            query{
              user(login: "ashutosh1919"){
                pullRequests(first:5, orderBy:{field: CREATED_AT, direction: DESC}){
                  nodes{
                    title
                  }
                }
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo `${{ steps.get_pull_requests_data.outputs.data }}` > pull_requests.json
          git add .
          git commit -m 'Pull requests updated'
          git push
