name: Github GraphQL API Query
on:
  push:
    branches:
      - master

jobs:
  pullRequestDataFetch:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.0.0
        id: get_pull_requests_data
        with:
          query: |
            query{
              user(login: "ashutosh1919"){
                pullRequests(first:5, orderBy:{field: CREATED_AT, direction: DESC}){
                  nodes{
                    title
                  }
                }
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: gr2m/get-json-paths-action@v1.0.1
        id: store_results
        with:
          json: ${{steps.get_pulll_requests_data.outputs}}
          name: "pull_requests.json"
          tag_name: "pull_requests_data"
          created_by: "author.login"
      - run: "echo latest release: `${{ steps.store_results.outputs.name }}` (`${{ steps.store_results.outputs.tag_name }}`) by `${{ steps.store_results.outputs.login }}`"
